name: New Competition Problem
description: Submit a new problem for the protein design competition
title: "New Problem: "
labels: ["new-problem"]
body:
  - type: markdown
    attributes:
      value: |
        ## Add a New Competition Problem

        Fill in the fields below to add a new problem.
        `config.json` will be updated automatically.

        **PDB file:** Provide the structure using ONE of these methods:
        1. **Server path** — absolute path to a PDB on the server
        2. **File upload** — drag-and-drop a `.pdb` file
        3. **Paste content** — paste raw PDB text with a filename

  - type: input
    id: problem_name
    attributes:
      label: Problem Name
      description: Display name for this problem
      placeholder: "e.g. 3-Helix Bundle"
    validations:
      required: true

  - type: dropdown
    id: problem_type
    attributes:
      label: Problem Type
      options:
        - monomer
        - binder
    validations:
      required: true

  - type: input
    id: session
    attributes:
      label: Session
      description: Session key this problem belongs to (e.g. week1, week2)
      placeholder: "week2"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Problem description shown to participants
      placeholder: "Design a sequence for a 3-helix bundle scaffold (73 residues)"
    validations:
      required: true

  - type: dropdown
    id: primary_metric
    attributes:
      label: Primary Metric
      description: Metric used for ranking
      options:
        - bb_lddt_cov
        - bb_lddt
        - tm_score
        - binder_lddt
        - interface_lddt
        - iptm
    validations:
      required: true

  - type: dropdown
    id: msa_mode
    attributes:
      label: MSA Mode
      description: MSA search mode for structure prediction
      options:
        - "none"
        - search
        - precomputed
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### PDB File (choose one method)

  - type: input
    id: pdb_server_path
    attributes:
      label: "Method 1: Server Path"
      description: Absolute path to a PDB file on the server (filename is derived automatically)
      placeholder: "/data/galaxy4/user/.../my-scaffold.pdb"

  - type: textarea
    id: pdb_upload
    attributes:
      label: "Method 2: File Upload"
      description: Drag-and-drop a .pdb file here

  - type: input
    id: pdb_filename
    attributes:
      label: "Method 3: Filename"
      description: Filename when pasting content below (e.g. my-scaffold.pdb)
      placeholder: "3H-scaffold.pdb"

  - type: textarea
    id: pdb_content
    attributes:
      label: "Method 3: Pasted PDB Content"
      description: Paste the full PDB file content here
      render: text

  - type: markdown
    attributes:
      value: |
        ---
        ### Binder-Only Fields
        Leave these blank for monomer problems.

  - type: textarea
    id: target_sequence
    attributes:
      label: Target Sequence
      description: Full amino acid sequence of the target protein (binder only)
      render: text

  - type: input
    id: expected_binder_length
    attributes:
      label: Expected Binder Length
      description: "Min and max residue count, e.g. 20,50"
      placeholder: "20,50"

  - type: input
    id: target_msa_path
    attributes:
      label: Target MSA Path
      description: Absolute path to precomputed .a3m file on the server (binder only)
      placeholder: "/data/galaxy4/user/.../target.a3m"
